# Independent settings for the local costmap
local_costmap:
  map_type: costmap

  global_frame    : odom
  robot_base_frame: base_footprint

  update_frequency : 5.0
  publish_frequency: 1.0

  static_map    : false
  rolling_window: true
  width         : 4.0
  height        : 4.0
  resolution    : 0.025

  robot_radius: 0.275

  #plugins are loaded on a separate file

  obstacle_laser_layer:
    enabled: true
    observation_sources: base_scan
    combination_method: 0 # can erase static layer

    base_scan:
      sensor_frame: base_laser_link
      data_type: LaserScan
      topic: scan
      expected_update_rate: 0.3
      observation_persistence: 1.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 4.0
      obstacle_range: 3.0

  obstacle_sonar_layer:
    enabled: false
    ns: ""
    topics: ["/sonar_base"]
    no_readings_timeout: 0.0
    clear_threshold: 0.20
    mark_threshold: 0.80
    clear_on_max_reading: true

  obstacle_rgbd_layer:
    enabled: true
    observation_sources: rgbd_scan
    combination_method: 1

    rgbd_scan:
      sensor_frame: base_footprint
      data_type: LaserScan
      topic: rgbd_scan
      expected_update_rate: 0.5
      observation_persistence: 0.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 3.5
      obstacle_range: 3.2
      blanking_range: 0.5
      min_obstacle_height: -0.1
      max_obstacle_height: 0.2
      debug: true

  inflation_layer:
    enabled            : true
    inflation_radius   : 0.55
    cost_scaling_factor: 5.0
