# Independent settings for the local costmap
local_costmap:
  map_type: costmap

  global_frame    : odom
  robot_base_frame: base_footprint
  transform_tolerance: 0.2

  update_frequency : 5.0
  publish_frequency: 2.0

  static_map    : false
  rolling_window: true
  width         : 5.0
  height        : 5.0
  resolution    : 0.05

  robot_radius  : 0.275
